package.json, src/constants.json, src/resolvers/index.ts, src/resolvers/selfid.ts, test/unit/resolvers/selfid.test.ts, yarn.lock
Closes: https://github.com/snapshot-labs/stamp/issues/1
Adds SelfID resolver.
Needs to use `https://ceramic-private.3boxlabs.com` as ceramic API, otherwise it will give you different DID and won't resolve the same avatar as self.id.
- Sign up at https://self.id/ and add your avatar.
- Go to http://localhost:3000/avatar/YOUR_ADDRESS (http://localhost:3000/avatar/0x556B14CbdA79A36dC33FcD461a04A5BCb5dC2A70)
- It gives you back your avatar (I've seen some issues that Snapshot's pinata would take long time to resolve this image (few minutes after first attempt it will start working).
=> feat: add SelfID resolver

package.json, tsconfig.json, yarn.lock
Closes: https://github.com/snapshot-labs/stamp/issues/21
- Upgrade TS to support syntax that SelfID deps use `import { type XYZ }`
- Add `skipLibCheck` to make TS ignore broken types in SelfID.
- `yarn && yarn build`
- `yarn start`
- http://localhost:3000/avatar/0x556B14CbdA79A36dC33FcD461a04A5BCb5dC2A70
=> fix: make build work after SelfID deps

src/constants.json, src/resolvers/index.ts, src/resolvers/lens.ts, test/unit/resolvers/lens.test.ts
Closes: https://github.com/snapshot-labs/stamp/issues/14
Adds [Lens.xyz](https://lens.xyz/) resolver. Couldn't test with my own account as it looks like it's not open yet for everyone.
- Disable `ens` resolver if you are testing with addresses that have the same image on `ens` as on `lens` so you can tell if it works or not.
- Try going to http://localhost:3000/avatar/fabien.lens
- It should return an image.
- Try going to http://localhost:3000/avatar/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7
- It should return an image.
=> feat: add Lens resolver

src/api.ts, test/unit/resolvers/selfid.test.ts
We read it from `key1/key2` and we wrote it to `key2/key1`.
=> fix: write resized images to correct location

src/api.ts, src/constants.json, src/utils.ts, test/unit/resolvers/ens.test.ts
Closes: https://github.com/snapshot-labs/stamp/issues/40
Currently we have couple of issues with how cache works:
- If fallback image is served it is still written to S3 so it will be stuck to fallback image forever (or as long as our S3 expiry policy is configured for) as cache takes priority. I don't think we should cache fallback images in S3 at all, instead just cache it at edge and just lower TTL for cache.
- Fallback gets TTL of 1 day which seems overly pessimistic, we can lower it to 1h, so if avatar is set (or some issue that caused it to fail to load no longer exists) it can update itself quicker.
- Setup local repo with AWS S3.
- Return false in space.ts
- Visit: http://localhost:3000/space/0xbattleground.eth?s=160 -> you get fallback image, Cache-Control is set to 3600
- Remove …
=> fix: lift cache on fallback images

.github/workflows/test.yml
Code coverage is not tracked by codecov
Upload the test coverage to codecov
- Add a new task in Github actions test workflow, to upload the coverage report after the test
- N/A
=> chore: update test coverage to codecov

.github/workflows/lint.yml, README.md, jest.config.ts, package.json, test/e2e/api.test.ts
This PR improve the test config:
- Collect coverage from all files, instead of only tested files
- Add test coverage badge to readme
- Separate lint and test task on github actions
=> chore: improve test config

src/resolvers/ens.ts
The current ENS resolver is returning the raw value from ENS, and it's working great when the value is an http url.
But when it's an NFT address, such as `eip155:1/erc1155:0x495f947276749Ce646f68AC8c248420045cb7b5e/61751686310106735452369515624497384717106902022558848289817630643456812515329` we should return `false`, and not continue with trying to fetch the image.
See https://github.com/snapshot-labs/stamp/issues/76
=> fix: return false when ENS avatar is not an URL

README.md
We just rebranded lenster.xyz to hey.xyz
https://twitter.com/heydotxyz/status/1707431312385253477
=> chore: rename lenster to hey

README.md
We just rebranded lenstube.xyz to tape.xyz 📼
https://twitter.com/tapexyz/status/1710259320418615518
cc @bonustrack
=> chore: rename lenstube to tape

src/api.ts
When clearing the cache, the `cb` query params is ignored
- Add the `cb` query params when computing the cache key
=> fix: fix missing `cb` query params when clearing cache

src/api.ts
Fix #124 
Fix [STAMP-8](https://snapshot-labs.sentry.io/issues/4654387973/?referrer=github_integration)
Errors sent to Sentry should always be an Error object
=> chore: object sent to sentry should be an Error object

src/addressResolvers/cache.ts
When all keys are already cached, the args passed to the callback function is an empty array
Fix #122 
Fix [STAMP-9](https://snapshot-labs.sentry.io/issues/4654544992/?referrer=github_integration)
We should skip calling the callback function when all keys are already cached
=> fix: skip resolver call when all addresses are already cached

src/addressResolvers/ens.ts, src/addressResolvers/index.ts, src/addressResolvers/lens.ts, src/addressResolvers/unstoppableDomains.ts, src/addressResolvers/utils.ts, test/unit/addressResolvers/index.test.ts
There's a high error rate since introduction of addressResolvers (https://snapshot-labs.sentry.io/issues/4651451195/?project=4505506866593792&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0)
Most of the errors come from invalid addresses given as params.
This PR will:
- ignore all invalid addresses, and process only valid one, instead of crashing and returning a 400 error for the whole request.
- log the addresses input given to the request, to debug why is there invalid addresses
=> fix: ignore invalid addresses

src/api.ts, src/aws.ts
- Not able to clear cache for images with `cb` param, for example https://cdn.stamp.fyi/space/wen%F0%9F%8C%95.eth?s=96&cb=c178562f8f12066b
- If there is nothing to clear, It returns `ok` in response 
How to test:
- Try going to http://localhost:3008/space/thanku.eth?s=160&cb=ce8ed162479340899ca4cae882bd0a0e
- Clear cache by going to http://localhost:3008/clear/space/thanku.eth?s=160&cb=ce8ed162479340899ca4cae882bd0a0e
=> fix: Clear cache doesn't work with `cb` param

src/addressResolvers/index.ts
Do not call lookupAddress resolvers when the address args is empty
=> fix: do not process functions on empty input

src/addressResolvers/ens.ts
Stop capturing error on invalid ENS parsing
=> chore: do not log error on invalid ENS name

src/addressResolvers/ens.ts, src/addressResolvers/lens.ts, src/addressResolvers/unstoppableDomains.ts, test/unit/addressResolvers/ens.test.ts, test/unit/addressResolvers/lens.test.ts, test/unit/addressResolvers/unstoppableDomains.test.ts, test/unit/addressResolvers/utils.ts
This PR validates handles input, and filter out invalid domains before calling the resolver.
- ENS handle validation coming from ens_normalize package
- Lens validation regex coming from their error graphql error message (`Expected value of type \"Handle!\", found \"Fabien@.lens\"; Handle only supports lower case characters, numbers, - and _. Handle must be minimum of 5 length and maximum of 31 length - fabien@.lens`)
- UnstoppableDomains validation regex coming from https://github.com/unstoppabledomains/resolution/blob/3c10dced96d25c7de5247ca5234a29d8c9699830/src/utils/prepareAndValidate.ts
=> fix: filter out invalid input before processing

src/addressResolvers/index.ts, test/unit/addressResolvers/index.test.ts
Current limit of addresses accepted for `lookupAddresses` is 250. This was a generous arbitrarily number chosen, without any rational.
We're now using graphql API to resolve the addresses, and they have a different limit
Decrease the number of accepted addresses, to match the resolvers API limit
- Lens limit is 50
- ENS limit is 1000
- Decrease the limit from 250 to 50 addresses. (this should not have any impact on UI, which is sending addresses in batch of 20)
=> fix: decrease max number of `lookupAddresses` params

src/addressResolvers/lens.ts
Migrate Lens API to v2
Current implementation is using v1.1 of their graphQL, and is highly unreliable, as it's returning ~200 503 and 502 errors per hour.
Some refactoring to format the handle, as the API is not expecting and returning a domain name anymore, but a handle formatted like `lens/HANDLE`
=> fix: use Lens v2 API

src/addressResolvers/ens.ts, src/addressResolvers/lens.ts, src/addressResolvers/unstoppableDomains.ts, src/addressResolvers/utils.ts
Timeout error are currently logged to Sentry, thus raising a lot of errors not related to code issues.
Fix #163 
Fix [STAMP-15](https://snapshot-labs.sentry.io/issues/4676915636/?referrer=github_integration)
Stop logging TIMEOUT errors (which we can do nothing about).
Instead, an alert has been added on the Grafana dashboard to trigger alert in case of slow response time.
- Add timeout to list of ignored errors on Sentry
=> chore: ignore TIMEOUT error

src/resolvers/ens.ts
Fix #76
Fix #109 
Fix missing image on ENS name, when the avatar metadata is not starting by `http`.
This fix uses ENS own metadata resolver as fallback, as pointed out here https://github.com/snapshot-labs/stamp/issues/109#issuecomment-1798361605
=> fix: fix ENS avatar resolver when avatar is not HTTP

src/addressResolvers/index.ts, src/addressResolvers/utils.ts, test/unit/addressResolvers/index.test.ts
Fix #155
Keep the original input case formatting when returning result
When sending `['a.eth', 'A.ETH']`, will return result like 
```ts
{
'a.eth': '0x0',
'A.ETH': '0x0'
}
```
-> return a value for each original input, to avoid any processing from the caller side, even if the address os the same. This is done only after getting result from api and caching, so we don't pass `a.eth` and `A.ETH` to api.
```bash
curl -X POST http://localhost:3008/ -H "Content-Type: application/json" -d '{"method": "resolve_names", "params": ["snapshot.crypto", "SNAPSHOT.CRYPTO"] }'
// result
{"jsonrpc":"2.0","result":{"snapshot.crypto":"0xeF8305E140ac520225DAf050e2f71d5fBcC543e7","SNAPSHOT.CRYPTO":"0xeF8305E140ac520225DAf050e2f71d5fBcC543e7"},"id":null}
```
```bash
curl -X POST http://localhost:3008/ -H …
```
=> fix: keep original input formatting when returning

src/addressResolvers/utils.ts
Fix #165 
Fix [STAMP-1J](https://snapshot-labs.sentry.io/issues/4868263621/?referrer=github_integration)
Remove null values before manipulation
=> fix: remove null values before processing

src/addressResolvers/utils.ts
When silencing timeout error, also take into account timeout error from brovider JsonRpcError
Also add `ECONNRESET` to list of silenced error (https://snapshot-labs.sentry.io/issues/4495021166/?project=4505506866593792&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=3)
=> fix: handle jsonRpcError when silencing contrat call errors

README.md, src/constants.json, src/resolvers/index.ts, src/resolvers/starknet.ts, test/unit/resolvers/starknet.test.ts
Add support for Starknet avatar from domain (see https://docs.starknet.id/devs/starknetid-api#domain-to-data)
Fix #175 
Test with 
- http://localhost:3008/avatar/checkpoint.stark
- http://localhost:3008/avatar/0x07FF6B17f07c4d83236E3Fc5f94259A19D1Ed41bBCf1822397EA17882E9b038d
Should return the same image
Coming later in another PR: resolving Starknet avatar from address
=> feat: add support for starknet avatar

src/aws.ts
Raise error when AWS client is not configured, for better error stacktrace
=> fix: raise error when AWS client is not configured

src/resolvers/farcaster.ts, test/integration/resolvers/farcaster.test.ts, yarn.lock
A lot of Farcaster avatars are hosted on imgur. Fetching the image from imgur is hitting a 429 rate limit.
Use a CDN to fetch image from imgur
- Add a function to return a CDN url when the image host is imgur.com
- Some minor coding style for consistency with other resolvers file
- Fix lint
- Fix yarn.lock with invalid version
=> fix: use CDN for imgur image

src/api.ts, src/constants.json, src/utils.ts
Add an optional `?resolver=` query params to `/avatar/[ID]` API endpoint, to target a specific resolver.
This is useful for testing, since we can fetch avatar from specific resolver directly, without editing the code.
With `?resolver=`, cache is disabled
This PR also fix avatar's resolving order, to be `["snapshot", "ens", "lens", "farcaster", "starknet"]`
- http://localhost:3008/avatar/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7?resolvers=ens
- http://localhost:3008/avatar/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7?resolvers=lens
- http://localhost:3008/avatar/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7?resolvers=farcaster
All these urls should return directly the avatar associated to the resolver.
=> feat: add query params to target avatar resolver

src/api.ts
Fix issue where the `?resolver=lens` query params is being ignored
=> fix: fix `resolver` query params being ignored

src/addressResolvers/utils.ts
Improve the filter capturing http 504 error.
This will let us capture 504 error returned by brovider
=> chore: capture more http 504 errors

test/.env.test
In test env. use 4everland instead of cloudflare as ipfs gateway, as cloudflare is always timing out, and failing tests
After this fix, `snapshot` and `space` resolvers should not fail in test anymore
=> fix: fix ipfs gateway always timing out on test env

src/resolvers/starknet.ts
Fix #216 
Fix an issue where all starknet was resolving on ETH address, thus making all addresses without images using the starknet fallback image
=> fix: ignore non-valid starknet address from starknet resolver

src/resolvers/space-sx.ts
Fix issue where some thegraph API are expecting checksum formatted addresses.
This PR will fix the issue by always passing both lowercase and checksumed address
=> fix: fix case sensitive graphql filter

src/api.ts, src/constants.json, src/resolvers/index.ts, src/resolvers/snapshot.ts, src/utils.ts, test/integration/resolvers/snapshot.test.ts
Related to the new profile page introduced in https://github.com/snapshot-labs/sx-monorepo/pull/394
An user has now a `cover` property, in addition to `avatar`, similar to the sx `Space` object.
This PR will add a new `user-cover` type when requesting image, allowing to fetch an user cover image with 
```
http://localhost:3008/user-cover/0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3
```
The `snapshot.ts` has been refactored to be similar to `space-sx.ts`
=> feat: add support for user cover

src/constants.json, src/utils.ts
This PR allow a larger max size for all image type including `-cover`.
Else, the newly introduced `user-cover` type is capped to only 500, but should behave like `space-cover-xxx`
=> fix: allow larger max size for all cover types

src/utils.ts
Using reduced quality greatly reduces image size (images are 90% smaller). Quality is reduced slightly, but not really noticable. You can try what quality 80 for WebP looks like on https://squoosh.app/
Closes: https://github.com/snapshot-labs/stamp/issues/243
=> feat: use lossy webp encoding (quality 80).

src/resolvers/snapshot.ts, src/utils.ts
We format user address before sending them to the hub, which is not needed anymore, as we've added the formatting directly on the hub side.
Remove address formatting, delegating the logic to the hub
Both urls should return the same image
- http://localhost:3008/avatar/0x91fd2c8d24767db4ece7069aa27832ffaf8590f3?resolver=snapshot
- http://localhost:3008/avatar/0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3?resolver=snapshot
=> fix: remove unecessary address formatting

src/addressResolvers/snapshot.ts, src/lookupDomains.ts, src/resolvers/lens.ts, src/resolvers/snapshot.ts, src/resolvers/space-sx.ts, src/resolvers/space.ts
This refactor is using the `graphQlCall` helper for all graphql calls
This will enable us in #265 to put the api key handling only inside this function
=> refactor: use graphql helper for all graphql calls

src/resolvers/space-sx.ts
Update the SX subgraph to the new `.box` domains, instead of old `x.xyz` domains
=> fix: update sx subgraph url

src/constants.json, src/resolvers/snapshot.ts, src/utils.ts, test/integration/resolvers/snapshot.test.ts
Closes https://github.com/snapshot-labs/workflow/issues/220
This PR adds support for testnet on the snapshot resolver (user-avatar, user-cover, space-cover, space-avatar)
This PR introduces a new address format (`NETWORK:ADDRESS`), e.g. `s:ens.eth` or `s-tn:0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3`, while still be backward compatible with the previous `ADDRESS` format
- Mainet space cover: http://localhost:3008/space-cover/test.wa0x6e.eth
- Mainet space cover: http://localhost:3008/space-cover/s:test.wa0x6e.eth 
- Testnet space avatar: http://localhost:3008/space/s-tn:diva-testing.eth
- Testnet user avatar: http://localhost:3008/avatar/s-tn:0x3b4e97c176DD99fE73307F123189F53EeF0BC435?resolver=snapshot (should be same as https://snapshot.4everland.link/ipfs/bafybeiaxlwymw6f76enjaf5errbybrf …
=> feat: add testnet support to snapshot resolver

src/api.ts, src/resolvers/snapshot.ts, src/utils.ts, test/integration/resolvers/snapshot.test.ts
Toward https://github.com/snapshot-labs/workflow/issues/220
This PR adds support for SX space and avatar in the snapshot resolver, and is the first step into merging all snapshot related resolver (snapshot and space-sx) into one single resolver.
This merging is now possible since https://github.com/stamp-labs/stamp/pull/308, which introduces network prefix for all IDs (e.g. `eth:0x00` or `s:snapshot.eth`), and enable network distinction from the ID itself.
Instead of having 
- `space-cover/ens.eth`
- `space-cover-sx/0x0xxxx` 
We could simply have 
- `space-cover/s:ens.eth`
- `space-cover/eth:0x0xxxx`
This update also improves the performance on the SX resolving side, since the network prefix enable us to target a specific API endpoint, instead of polling all SX endpoint on each request. …
=> feat: add SX support in snapshot resolver

src/utils.ts
This PR fix an issue where the legacy url for the `space/ADDRESS` endpoint (without network prefix) was not working as intended, due to an issue when setting the missing network prefix 
This result in those 2 url not returning the same result
- http://localhost:3008/space/s:test.wa0x6e.eth?resolver=space
- http://localhost:3008/space/test.wa0x6e.eth?resolver=space
=> fix: fix legacy snapshot resolver not working

test/e2e/api.test.ts, test/integration/resolvers/snapshot.test.ts
This PR adds some tests to ensure that the snapshot resolver legacy format (space/address) always return same result as the new one (space/network:address), for both v1 and sx
=> test: add more tests for snapshot legacy format

src/resolvers/snapshot.ts, src/resolvers/space-sx.ts
Toward https://github.com/snapshot-labs/workflow/issues/331
Update SX APIs urls to use subgrapher, to avoid rate limit
=> fix: update urls to SX api

src/constants.json, src/resolvers/coingecko.ts, src/resolvers/index.ts
This pull request introduces a new resolver for tokens using CoinGecko API, this get a much wider coverage than trustwallet or zapper, including tokens on Base like AIXBT or USDC. The config var `COINGECKO_API_KEY` is already available in DigitalOcean, I can share it to you by PM.
Closes https://github.com/snapshot-labs/workflow/issues/346
- Disable cache
- Try AIXBT on Base: http://localhost:3008/token/eip155:8453:0x4f9fd6be4a90f2620860d680c0d4d5fb53d1a825?s=64
- Try USDC on Base: http://localhost:3008/token/eip155:8453:0x833589fcd6edb6e08f4c7c32d4f71b54bda02913?s=64
=> feat: add CoinGecko token image resolver

src/addressResolvers/index.ts, src/addressResolvers/utils.ts, test/integration/addressResolvers/utils.test.ts
Fix #336
Fix issue where using `lookup_address` on the empty address `0x0000000000000000000000000000000000000000` was returning a handle for that address.
This handle is currently coming from lens, which is returning all those results when querying this empty address
```json
{
'0xf7a9c91e71EE61c82395Ec85ec2bb5313CD52FFc': 'aleyy.lens',
'0xcdb631b220cC680F8d756b3A0a0f4c1C271887a2': 'andy188.lens',
'0x944b12BE4048294fcB3b3f760E0aBaf5D0aAF099': '0xmoc.lens',
'0x3da94A101245B9b3815f1DdeCD532bc335a9361C': 'brave361.lens',
'0xAB0e4Da0A57A3eBf7f7c84fB618698Cff9BCd936': '6jioper.lens',
'0x4c8B3A2f23C377bC90288a38068EEB23050Ae709': '0xlusifer.lens',
'0x14d9b0d725b96bE978eDadC322b6E20C74dCBCA7': '0o960.lens',
'0x0ce2895AA13E7536668fD660BD1742f3510F31C3': 'roico14.lens', …
```
=> fix: exclude empty address from lookup_address

src/addressResolvers/unstoppableDomains.ts, src/addressResolvers/utils.ts
Depends on https://github.com/snapshot-labs/snapshot.js/pull/1114
This PR will use the new option in the SDK to set a custom timeout when connecting to brovider.
This will let us set the same timeout value (5 seconds) for all address resolvers.
UnnstoppableDomain not having a timeout was making all address resolvers request respond after 25 seconds, when brovider node is having issues.
=> fix: set timeout for unstoppable domains resolver

src/api.ts, src/utils.ts
Toward https://github.com/snapshot-labs/sx-monorepo/pull/1153
This PR adds a new query params `fit` when querying image, to control how the image is resized.
It accepts any values accepted by https://sharp.pixelplumbing.com/api-resize#resize (`contain`, `cover`, etc).
The current fit (cover) is not always ideal, as sometimes, we need the image in its original ratio
- Go to http://localhost:3008/space-cover/test.wa0x6e.eth?h=200&w=300&fit=fill
- Go to http://localhost:3008/space-cover/test.wa0x6e.eth?h=200&w=300&fit=inside
It should return images with different resize ratio (missing `fit` query params will default to `cover`)
=> feat: add params to customize resize fit

src/addressResolvers/ens.ts
Toward https://github.com/snapshot-labs/workflow/issues/485
Add support for ENS names offchain resolution
```shell
curl --location 'http://localhost:3008' \
--header 'Content-Type: application/json' \
--data '{
"method": "resolve_names",
"params": [
"defi.app",
"lucemans.cb.id",
"lucemans.uni.eth",
"ulas.clv.eth",
"lucemans.lens.xyz"
]
}' | jq
``` 
It should now return results
```json
{
"jsonrpc": "2.0",
"result": {
"defi.app": "0x7aeB96261e9dC2C9f01BaE6A516Df80a5a98c7eB",
"lucemans.cb.id": "0x4e7abb71BEe38011c54c30D0130c0c71Da09222b",
"lucemans.uni.eth": "0x225f137127d9067788314bc7fcc1f36746a3c3B5",
"ulas.clv.eth": "0xd883E2d407361049dd3DACE2fF4278D75BC11d2A"
},
"id": null
}
```
=> feat: add support for offchain ens name resolving

src/resolvers/snapshot.ts
Closes: https://github.com/snapshot-labs/workflow/issues/509
=> feat: add mnt, ape, curtis networks to snapshot resolver

src/lookupDomains/index.ts
Right now UI send chainIds as Int, we need to convert it into string
Send request with:
```bash
curl --location 'http://localhost:3008' \
--header 'Content-Type: application/json' \
--data '{
"method": "lookup_domains",
"params": "0x24F15402C6Bb870554489b2fd2049A85d75B982f",
"network": 1
}'
```
=> fix: make sure chainIds are strings and unique

src/addressResolvers/lens.ts, src/addressResolvers/utils.ts
Fix #364 
Stop capturing lens 503 errors
These errors are too frequent, eating our errors quota on sentry, and we don't have any way to solve them, since their api is free and without auth
=> fix: mute server error from lens

src/addressResolvers/lens.ts
Fix https://snapshot-labs.sentry.io/issues/4651451195/events/latest/?notification_uuid=94935e9b-e1ed-438b-abfa-5941ed814c91&project=4505506866593792&referrer=latest-event
This PR will stop logging errors when lens api is returning 429 response.
Those errors can not be fixed, and are just consuming sentry quota
=> fix: mute 429 errors from lens

.github/workflows/test.yml, package.json, src/constants.json, src/getOwner/shibarium.ts, src/lookupDomains/shibarium.ts, test/integration/getOwner.test.ts, yarn.lock
This PR fix an issue with unclaimed .shib names.
.shib names can be bought with web2 means, such as credit card. Names bought via such mean will not be associated to an EOA wallet, and retrieving the owner via d3 api will not return owner field.
In those cases, we should fallback, and return the resolved address instead, and consider the resolved address as owner, like we already do with the other offchain resolved address (like coinbase .cb.id names).
This will fix the error encountered in the ui pr: https://github.com/snapshot-labs/sx-monorepo/actions/runs/14441352799/job/40492017489?pr=1312
Resolving names are done via https://docs.d3.app/resolve-d3-names#d3-connect-sdk
```shell
curl --location 'http://localhost:3008' \
--header 'Content-Type: application/json' \
--data '{
"method": …
```
=> fix: handle unclaimed names when fetching shib names owner

src/addressResolvers/index.ts, src/addressResolvers/shibarium.ts, test/integration/addressResolvers/shibarium.test.ts
Towards https://github.com/snapshot-labs/workflow/issues/523
This PR adds shibarium to the `lookup_addresses` and `resolve_name`
disable the other resolver:
```diff
diff --git a/src/addressResolvers/index.ts b/src/addressResolvers/index.ts
index 7987d57..ed509c2 100644
--- a/src/addressResolvers/index.ts
+++ b/src/addressResolvers/index.ts
@@ -16,11 +16,11 @@ import { Address, Handle } from '../utils';
import { timeAddressResolverResponse as timeResponse } from '../helpers/metrics';
const RESOLVERS = [
-  snapshotResolver,
-  ensResolver,
-  unstoppableDomainResolver,
-  lensResolver,
-  starknetResolver,
+  // snapshotResolver,
+  // ensResolver,
+  // unstoppableDomainResolver,
+  // lensResolver,
+  // starknetResolver,
shibariumResolver
];
const MAX_LOOKUP_ADDRESSES = 50;
```
```shell …
```
=> feat: resolve shibarium names and addresses

src/lookupDomains/ens.ts, src/lookupDomains/index.ts, src/lookupDomains/shibarium.ts
When running the `lookup_domains`, like 
```shell
curl --location 'http://localhost:3008' \
--header 'Content-Type: application/json' \
--data '{
"method": "lookup_domains",
"params":
"0x220bc93D88C0aF11f1159eA89a885d5ADd3A7Cf6"
}' | jq
```
it currently only returns ens name, since when missing, the networks params default to `1`
This PR fix the issue by adding shibarium chain id to the default list
=> fix: lookup_domains should default to use all supported mainnet

.claude/settings.local.json, src/lookupDomains/shibarium.ts
This PR fix an issue where the shibarium wallet own more than 25 domains, in which cases, the results from `domain_lookup` will only return max 25 items, due to pagination not being implemented.
This PR will handle pagination when fetching results, as well as some fetching improvement:
- add timeout of 10s for each requests (data are not cached, so user may retry in case some results are missing)
- better error handling, to not return empty data in case requests fail mid-pagination
```shell
curl 'http://localhost:3008/' \
-H 'content-type: application/json' \
--data-raw '{"method":"lookup_domains","params":"0xc7D0445ac2947760b3dD388B8586Adf079972Bf3","network":109}'
```
It should return some results (have not found any wallets owning more than 25, you can try changing the `limit` in the …
=> fix: handle pagination when fetching shibarium domain lookup

test/integration/resolvers/ens.test.ts, test/setup-jest.ts
Fix tests:
- ENS tests were testing using `snowowl.eth` name, which is now broken with the error `{"message":"Error fetching avatar: Provided url or NFT source is broken."}` (see https://metadata.ens.domains/mainnet/avatar/snowowl.eth). Tests switched to use `fabien.eth` instead
- Mute `console.log` in test output
This PR is fixing some of the failing tests, remaining failing tests are due to another code issue, which will be addressed in another PR (https://github.com/stamp-labs/stamp/pull/380)
=> test: fix failing test due to invalid test data

src/resolvers/coingecko.ts
- added apechain to the asset platforms list
- https://cdn.stamp.fyi/token/eip155:33139:0xd6e4df460d9ba104dfc5dc57db392c177083d20c?s=64 - Doesn't work
- http://localhost:3008/token/eip155:33139:0xd6e4df460d9ba104dfc5dc57db392c177083d20c?s=64 - Should work
=> fix: add support for apechain in Coingecko resolver

src/resolvers/snapshot.ts
This PR fix an issue where the space-logo image was forced to a square ratio
After this fix, space-logo can have any ratio
- Go to http://localhost:3008/space-logo/openagora.eth?w=190&h=38&fit=inside
- The image should not be square anymore
=> fix: space-logo image should not be cropped to a square image

src/lookupDomains/unstoppableDomains.ts, test/integration/lookupDomains.test.ts
The unstoppable domains lookup was using a custom chain id `unstoppable-domain`, since it was created to return domains from various chain ids.
It was now refactored to return only .sonic domain name, this PR will update the accepted chain id to 146 (sonic chain id)
=> fix: use sonic chain id when asking for .sonic domains

src/addressResolvers/index.ts, src/api.ts
The address resolver cache clearing is currently only handling addresses, and will reject input when passing names (e.g. snapshot.org).
This PR fix the cache clearing function to also handle domain names
=> fix: fix cache clearing for resolved names

src/resolvers/snapshot.ts, test/integration/resolvers/space-sx.test.ts
This PR removes the polygon network from the list of supported network by snapshot-x api
Resolver is dead since the removal of the polygon network on sx, leading to failing test.
=> chore: remove polygon from snapshot resolver

package.json, src/addressResolvers/index.ts, src/addressResolvers/spaceId.ts, src/addressResolvers/unstoppableDomains.ts, src/utils.ts, test/integration/addressResolvers/spaceId.test.ts, yarn.lock
Closes https://github.com/snapshot-labs/stamp/issues/410
This PR adds the support for resolving:
- address -> .bnb name
- .bnb name -> address 
Which will allow the snapshot UI to display .bnb name associated to an address.
```bash
curl \
-X POST \
-H 'Content-Type: application/json' \
-d '  {
"method": "lookup_addresses",
"params": ["0x220bc93D88C0aF11f1159eA89a885d5ADd3A7Cf6", "0xb5932a6B7d50A966AEC6C74C97385412Fb497540", "0x2e552E3aD9f7446e9caB378c008315E0C26c0398"]
}' \
'http://localhost:3008'
```
Will return 
```json
{
"jsonrpc": "2.0",
"result": {
"0x220bc93D88C0aF11f1159eA89a885d5ADd3A7Cf6": "boorger.eth",
"0xb5932a6B7d50A966AEC6C74C97385412Fb497540": "spaceid.bnb",
"0x2e552E3aD9f7446e9caB378c008315E0C26c0398": "allen.bnb"
},
"id": null
}
```
NOTE: first one (`boorger.eth`) will …
=> feat: add .bnb names resolver
