snapshot-labs/stamp

package.json
src/api.ts
src/constants.json
src/resolvers/index.ts
src/resolvers/jazzicon.ts
src/utils.ts
test/unit/resolvers/jazzicon.test.ts
yarn.lock

Closes https://github.com/snapshot-labs/stamp/issues/2
- http://localhost:3000/avatar/0x290ADCcA6253aCe88b10A6bb34C07a5Ad10fC6B0 returns blockie fallback
- http://localhost:3000/avatar/0x290ADCcA6253aCe88b10A6bb34C07a5Ad10fC6B0?fb=jazzicon returns jazzicon fallback
- Test with your own address, it should look identical to your address in metamask

feat: add Jazzicon resolver

---

src/constants.json
src/resolvers/index.ts
src/resolvers/zapper.ts
src/utils.ts
test/unit/resolvers/zapper.test.ts

Closes: https://github.com/snapshot-labs/stamp/issues/26

feat: add zapper resolver

---

README.md

Integration PR: https://github.com/lensterxyz/lenster/pull/636

chore: add lenster to integrations list

---

README.md

They are using this service as well!

doc: add RSS3 into the integration list

---

src/aws.ts

Change path on AWS to fix cache issue with resized images

fix: change path on AWS

---

src/api.ts
src/constants.json
src/resolvers/index.ts
src/resolvers/space-sx.ts

Related https://github.com/snapshot-labs/sx-ui/issues/419

feat: add space-sx resolver

---

src/api.ts
src/utils.ts

Context: https://github.com/snapshot-labs/sx-ui/issues/640#issuecomment-1556941037

fix: include cb param in cache key

---

src/api.ts
src/constants.json
src/resolvers/index.ts
src/resolvers/space-sx.ts
src/utils.ts

Needs new subgraphs to be deployed (https://github.com/snapshot-labs/sx-subgraph/pull/29)
- http://localhost:3000/space-cover-sx/0x62f8a028433d811cc0a63c974207276600322062?w=1400&h=140

feat: add space-sx cover resolver

---

.env.example
package.json
src/api.ts
src/index.ts
src/sentry.ts
yarn.lock

chore: send errors to sentry

---

src/resolvers/ens.ts
src/utils.ts
test/unit/resolvers/ens.test.ts

fix: fix failing ENS resolver

---

src/resolvers/trustwallet.ts
src/resolvers/zapper.ts
src/utils.ts

Check http://localhost:3000/token/eip155:137:0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee?s=64 returns Matic icon.

feat: handle Matic token icon

---

src/resolvers/snapshot.ts
src/utils.ts
test/unit/resolvers/snapshot.test.ts

Increase test timeout for tests relying on slow API

chore: fix tests

---

src/addressResolvers/ens.ts

Ens like https://app.ens.domains/volet.eth doesn't have a resolved address

fix: Some ENS doesn't have resolved address

---

src/addressResolvers/ens.ts
src/addressResolvers/lens.ts
src/addressResolvers/unstoppableDomains.ts

`capture` for sentry logging does not work, should be an object of object.

fix: fix sentry logging

---

src/addressResolvers/utils.ts

Explicitly set a timeout for axios connections

fix: decrease timeout

---

src/addressResolvers/utils.ts
src/resolvers/ens.ts
src/resolvers/lens.ts
src/resolvers/selfid.ts
src/resolvers/snapshot.ts
src/resolvers/space-sx.ts
src/resolvers/space.ts
src/resolvers/trustwallet.ts
src/resolvers/utils.ts
src/resolvers/zapper.ts

- Improve the axios fetch request by adding timestamp and keepAlive
- Refactor image resolvers by extracting the axios image fetcher to utils.ts

refactor: improve axios connection

---

src/addressResolvers/utils.ts

Silence 504 (timeout) error code, returned by brovider as JSON-RPC error

fix: silence 504 error code from provider

---

src/resolvers/ens.ts

Stamp avatar is not returning the avatar associated to the ENS name when passing an ETH address, instead of ENS name
This does not work: http://localhost:3008/avatar/0x839395e20bbB182fa440d08F850E6c7A8f6F0780
This works: http://localhost:3008/avatar/griff.eth
There are some rare case where it work in the current setup, thanks to the Lens resolver being able to resolve both ETH address and ENS name. The ENS resolver never worked when passing an ETH address 🙈
Fix #184
When passing an address to the ENS resolver, try to lookup the name associated to the address first, and use the returned ENS name to resolve the avatar.
- Add `castToEnsName` function to ENS resolver, to ensure we always resolve an ENS name
Disable your cache first (comment the AWS lines in your .env)
Both of these addresses …

fix: fix ENS avatar not resolving when passing address

---

src/resolvers/farcaster.ts
test/integration/resolvers/farcaster.test.ts

Current farcaster resolver code has been submitted by an external developer, from bounty.
Code is working, but there's a few issues with coding style and standard, that have been overlooked when merging the PR, to save time.
- Refactor code to adhere to same coding style and standard as other resolvers
- Remove most of the console.error
- Tests should pass (tests are failing on CI due to missing API key)
- You can test a farcaster avatar with http://localhost:3008/avatar/0xd1a8Dd23e356B9fAE27dF5DeF9ea025A602EC81e (disable all the other resolvers in constants.json)

refactor: refactor code to adhere to current coding style

---

src/resolvers/lens.ts
test/integration/resolvers/lens.test.ts

Fix lens avatar not working, due to lens v1 API being sunset.
Move to use Lens API-v2
- Migrate code to use new v2 lens api
- http://localhost:3008/avatar/fabien.lens?resolver=lens
- http://localhost:3008/avatar/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7?resolver=lens
- It should return an avatar
- Lens tests should pass

fix: fix lens avatar not working

---

package.json
src/resolvers/starknet.ts
test/integration/resolvers/snapshot.test.ts
test/integration/resolvers/starknet.test.ts
yarn.lock

Fix #230 
Fix issue where starknet avatar where not working.
The call to the contract was returning an exception, upgrading the lib to the latest version fixed the issue

fix: fix starknet avatar not working

---

src/constants.json
src/lookupDomains.ts

Update ENS sepolia subgraph url

fix: fix deprecated sepolia subgraph url

---

src/api.ts
src/constants.json
src/resolvers/index.ts
src/resolvers/snapshot.ts
src/utils.ts

Toward https://github.com/snapshot-labs/workflow/issues/416
This PR adds support for resolving a space logo (for whitelabel)
Test with http://localhost:3008/space-logo/test.wa0x6e.eth (need a space with logo)

feat: add support for space logo

---

jest.config.ts
test/setup-jest.ts

allow test to retry on failure

test: allow tests to retry

---

src/api.ts

This PR will stop sending the error when it's an user error (code 400)

chore: stop capturing user error
